Removes "sudo" in Docker build instructions.
tox4j/apidsl pull request #35
Opened 2019-06-09 11:54 UTC by antis81

We can assume the user is in the "docker" group -> Docker default installation.

2019-06-11 02:04 UTC, nurupo commented
Docker build on Travis-CI fails in your last commit.

2019-06-11 10:18 UTC, antis81 commented
@nurupo Thanks! Argh… latest Debian stable is still "stretch" - got a little confused with "buster".

2019-06-11 10:34 UTC, antis81 commented
@nurupo Docker build is ok.

Why does it fail on host :question:

```text
ocaml setup.ml -build -yaccflags --table
+ ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package ppx_driver.ocamlbuild myocamlbuild.ml /home/travis/.opam/default/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
ocamlfind: Package `ppx_driver.ocamlbuild' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
E: Failure("Command ''/home/travis/.opam/default/bin/ocamlbuild' apigen.native -use-ocamlfind -plugin-tag 'package(ppx_driver.ocamlbuild)' -tag debug -tag tests -yaccflags --table' terminated with error code 10")
make[1]: *** [build] Error 1
make[1]: Leaving directory `/home/travis/build/TokTok/apidsl/src/.coverage'
~/build/TokTok/apidsl/src
make: *** [coverage] Error 2
make: Leaving directory `/home/travis/build/TokTok/apidsl/src'
The command "make -C src coverage" exited with 2.
```

2019-06-11 18:15 UTC, nurupo commented
The build was failing not because Buster is not Stable yet, but because:

```
bwrap: Creating new namespace failed: Operation not permitted
```

Somehow this error doesn't get triggered on Jessie and Stretch.

Also, there is little reason in bumping the distro version, since all the container does is build the apidsl binary. You actually want to use as old distro as possible, to make sure its glibc would be compatible with yours, as the apidsl binary produced is not statically linked.

2019-07-11 13:07 UTC, antis81 commented
@nurupo Reverted the update change -> same result. Seems like a "ppx driver" is missing or something.

2020-03-22 00:50 UTC, iphydf approved these changes

2020-03-22 00:51 UTC, iphydf requested changes
It doesn't work now. It seems to be missing unzip, so you should install that (or keep buster).

2021-12-03 02:19 UTC, iphydf approved these changes

2021-12-03 02:19 UTC, merged